routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/app', function () {
    return view('app');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/users', 'UsersController')->middleware(['auth']);

Route::resource('/books', 'BooksController');

Route::resource('/loaisachs', 'LoaisachsController');
Route::resource('/nhaxuatbans', 'NhaxuatbansController');
Route::resource('/tacgias', 'TacgiasController');

Route::resource('/carts', 'CartsController')->middleware(['auth']);

Route::get('/about', function () {
    return view('about');
})->name('about');

resources/views/exam1/default.blade.php
<!doctype html>
<html class="no-js" lang="zxx">
@include('exam1.head')
<body>
<!--[if lte IE 9]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please
    <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
<![endif]-->

<!-- Main wrapper -->
<div class="wrapper" id="wrapper">
    <!-- Header -->
@include('exam1.header')
<!-- End Header -->
    <!-- Start BEst Seller Area -->
@yield('content')
    <!-- Footer Area -->
@include('exam1.footer')
<!-- //Footer Area -->

</div>
<!-- //Main wrapper -->

<!-- JS Files -->
<script src="{{ asset('js/vendor/jquery-3.2.1.min.js') }}"></script>
<script src="{{ asset('js/popper.min.js') }}"></script>
<script src="{{ asset('js/bootstrap.min.js') }}"></script>
<script src="{{ asset('js/plugins.js') }}"></script>
<script src="{{ asset('js/active.js') }}"></script>

</body>
</html>

resources/views/exam1/footer.blade.php

<footer id="wn__footer" class="footer__area bg__cat--8 brown--color">
    <div class="footer-static-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer__widget footer__menu">
                        <div class="ft__logo">
                            <a href="index.html">
                                <img src="{{ asset('img/logo/3.png') }}" alt="logo">
                            </a>
                            <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered duskam alteration variations of passages</p>
                        </div>
                        <div class="footer__content">
                            <ul class="social__net social__net--2 d-flex justify-content-center">
                                <li><a href="#"><i class="bi bi-facebook"></i></a></li>
                                <li><a href="#"><i class="bi bi-google"></i></a></li>
                                <li><a href="#"><i class="bi bi-twitter"></i></a></li>
                                <li><a href="#"><i class="bi bi-linkedin"></i></a></li>
                                <li><a href="#"><i class="bi bi-youtube"></i></a></li>
                            </ul>
                            <ul class="mainmenu d-flex justify-content-center">
                                <li><a href="#">Trending</a></li>
                                <li><a href="#">Best Seller</a></li>
                                <li><a href="#">All Product</a></li>
                                <li><a href="#">Wishlist</a></li>
                                <li><a href="#">Blog</a></li>
                                <li><a href="#">Contact</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="copyright__wrapper">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-12">
                    <div class="copyright">
                        <div class="copy__right__inner text-left">
                            <p>Copyright <i class="fa fa-copyright"></i>
                                <a href="https://freethemescloud.com/">Free themes Cloud.</a> All Rights Reserved
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-12">
                    <div class="payment text-right">
                        <img src="{{ asset('img/icons/payment.png') }}" alt=""/>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

resources/views/exam1/head.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>@yield('title')</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Favicons -->
    <link rel="shortcut icon" href="{{ asset('img/favicon.ico') }}">
    <link rel="apple-touch-icon" href="{{ asset('img/icon.png') }}">

    <!-- Google font (font-family: 'Roboto', sans-serif; Poppins ; Satisfy) -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,300i,400,400i,500,600,600i,700,700i,800" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">

    <!-- Stylesheets -->
    <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/plugins.css') }}">
    <link rel="stylesheet" href="{{ asset('css/style.css') }}">

    <!-- Cusom css -->
    <link rel="stylesheet" href="{{ asset('css/custom.css') }}">

    <!-- Modernizer js -->
    <script src="{{ asset('js/vendor/modernizr-3.5.0.min.js') }}"></script>

    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <script src="{{ asset('js/app.js') }}" defer></script>
</head>

resources/views/exam1/header.blade.php
<header id="wn__header" class="header__area header__absolute sticky__header">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 col-sm-6 col-6 col-lg-2">
                <div class="logo">
                    <a href="{{ route('home') }}">
                        <img src="{{ asset('img/logo/logo.png') }}" alt="logo images">
                    </a>
                </div>
            </div>
            <div class="col-lg-8 d-none d-lg-block">
                <nav class="mainmenu__nav">
                    <ul class="meninmenu d-flex justify-content-start">
                        <li class="drop with--one--item"><a href="{{ route('home') }}">Home</a></li>

                        <li class="drop"><a href="/books">Books</a>
                            <div class="megamenu mega03">
                                <ul class="item item03">
                                    <li><a class="title" href="/loaisachs">Categories</a></li>
                                    <li><a href="/loaisachs/1">truyện cười </a></li>
                                    <li><a href="/loaisachs/2">truyện trinh thám </a></li>
                                    <li><a href="/loaisachs/3">truyện cổ tích </a></li>
                                    <li><a href="/loaisachs/4">truyện ngụ ngôn </a></li>
                                    <li><a href="/loaisachs/5">sách tâm lý </a></li>
                                </ul>
                                <ul class="item item03">
                                    <li><a class="title">Customer Favourite</a></li>
                                    <li><a href="#">Mystery</a></li>
                                    <li><a href="#">Religion & Inspiration</a></li>
                                    <li><a href="#">Romance</a></li>
                                    <li><a href="#">Fiction/Fantasy</a></li>
                                    <li><a href="#">Sleeveless</a></li>
                                </ul>
                                <ul class="item item03">
                                    <li><a class="title">Collections</a></li>
                                    <li><a href="#">Science </a></li>
                                    <li><a href="#">Fiction/Fantasy</a></li>
                                    <li><a href="#">Self-Improvemen</a></li>
                                    <li><a href="#">Home & Garden</a></li>
                                    <li><a href="#">Humor Books</a></li>
                                </ul>
                            </div>
                        </li>

                        @canany(['admin','staff'])
                            <li><a href="{{ route('loaisachs.index') }}">Book Type</a></li>
                        @endcanany
                        <li><a href="{{ route('tacgias.index') }}">Tac Gia</a></li>
                        <li><a href="{{ route('nhaxuatbans.index') }}">Nha Xuat Ban</a></li>
                        <li><a href="{{ route('about') }}">About Us</a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-md-6 col-sm-6 col-6 col-lg-2">
                <ul class="header__sidebar__right d-flex justify-content-end align-items-center">
                    <li class="shop_search"><a class="search__active" href="#"></a></li>
                    <li class="wishlist"><a href="#"></a></li>
                    <li class="shopcart"><a class="" href="{{ route('carts.index') }}"></a></li>
                    <li class="setting__bar__icon"><a class="setting__active" href="#"></a>
                        <div class="searchbar__content setting__block">
                            <div class="content-inner">
                                <div class="switcher-currency">
                                    @guest()
                                        <a class="label switcher-label" href="{{ route('login') }}">
                                            <span>Sign In</span>
                                        </a>
                                        <a class="label switcher-label" href="{{ route('register') }}">
                                            <span>Register</span>
                                        </a>
                                    @else
                                        <strong class="label switcher-label">
                                            <span>{{ Auth::user()->name }}</span>
                                        </strong>
                                        <div class="switcher-options">
                                            <div class="switcher-currency-trigger">
                                                @canany(['admin','staff'])
                                                    <a class="currency-trigger" href="{{ route('users.index') }}">Manager</a>
                                                @endcanany
                                                <a class="currency-trigger" href="{{ route('users.show',Auth::user()->id) }}">Your Profile</a>
                                                <a class="currency-trigger" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">Log out</a>
                                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                                    @csrf
                                                </form>
                                            </div>
                                        </div>
                                    @endguest
                                </div>

                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <!-- Start Mobile Menu -->
        <div class="row d-none">
            <div class="col-lg-12 d-none">
                <nav class="mobilemenu__nav">
                    <ul class="meninmenu">
                        <li><a href="{{ route('home') }}">Home</a></li>
                        <li><a href="#">Pages</a>
                            <ul>
                                <li><a href="about.html">About Page</a></li>
                                <li><a href="portfolio.html">Portfolio</a>
                                    <ul>
                                        <li><a href="portfolio.html">Portfolio</a></li>
                                        <li><a href="portfolio-details.html">Portfolio Details</a></li>
                                    </ul>
                                </li>
                                <li><a href="my-account.html">My Account</a></li>
                                <li><a href="cart.html">Cart Page</a></li>
                                <li><a href="checkout.html">Checkout Page</a></li>
                                <li><a href="wishlist.html">Wishlist Page</a></li>
                                <li><a href="error404.html">404 Page</a></li>
                                <li><a href="faq.html">Faq Page</a></li>
                                <li><a href="team.html">Team Page</a></li>
                            </ul>
                        </li>
                        <li><a href="#">Shop</a>
                            <ul>
                                <li><a href="#">Shop Grid</a></li>
                                <li><a href="single-product.html">Single Product</a></li>
                            </ul>
                        </li>
                        <li><a href="blog.html">Blog</a>
                            <ul>
                                <li><a href="blog.html">Blog Page</a></li>
                                <li><a href="blog-details.html">Blog Details</a></li>
                            </ul>
                        </li>
                        <li><a href="contact.html">Contact</a></li>
                    </ul>
                </nav>
            </div>
        </div>
        <!-- End Mobile Menu -->
        <div class="mobile-menu d-block d-lg-none">
        </div>
        <!-- Mobile Menu -->
    </div>
</header>

<!-- Start Search Popup -->
<div class="brown--color box-search-content search_active block-bg close__top">
    <form id="search_mini_form" class="minisearch" action="{{ route('books.index') }}">
        <div class="field__search">
            <div class="row">
                <div class="col-auto">
                    <input class="form-control mr-sm-0" type="search" placeholder="book name" name="name" value="{{ request('name') }}">
                </div>
                <div class="col-auto">
                    <input class="form-control mr-sm-0" type="number" placeholder="min price" name="min_price" value="{{ request('min_price') }}">
                </div>
                <div class="col-auto">
                    <input class="form-control mr-sm-0" type="number" placeholder="max price" name="max_price" value="{{ request('max_price') }}">
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-auto">
                    <select class="browser-default custom-select mr-sm-0" name="loaisach_id">
                        <option value="">book type</option>
                        @foreach(\App\Models\Loaisach::pluck('name', 'id')->toArray() as $key => $value)
                            <option value="{{ $key }}" {{ ((request('loaisach_id') ?? 0) == $key) ? 'selected' : '' }}>{{ $value }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-auto">
                    <select class="browser-default custom-select mr-sm-0" name="tacgia_id">
                        <option value="">Tac gia</option>
                        @foreach(\App\Models\tacgia::pluck('name', 'id')->toArray() as $key => $value)
                            <option value="{{ $key }}" {{ ((request('tacgia_id') ?? 0) == $key) ? 'selected' : '' }}>{{ $value }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-auto">
                    <select class="browser-default custom-select mr-sm-0" name="nhaxuatban_id">
                        <option value="">Nha xuat ban</option>
                        @foreach(\App\Models\Nhaxuatban::pluck('name', 'id')->toArray() as $key => $value)
                            <option value="{{ $key }}" {{ ((request('nhaxuatban_id') ?? 0) == $key) ? 'selected' : '' }}>{{ $value }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <button class="btn btn-primary my-2 my-sm-10 container d-flex justify-content-center" type="submit">Search</button>
        </div>
    </form>
    <div class="close__wrap">
        <span>close</span>
    </div>
</div>
<!-- End Search Popup -->
<!-- Start Slider area -->
<div class="slider-area brown__nav slider--15 slide__activation slide__arrow01 owl-carousel owl-theme">
    <!-- Start Single Slide -->
    <div class="slide animation__style10 bg-image--1 fullscreen align__center--left">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="slider__content">
                        <div class="contentbox">
                            <h2>Buy <span>your </span></h2>
                            <h2>favourite <span>Book </span></h2>
                            <h2>from <span>Here </span></h2>
                            {{--                            <a class="shopbtn" href="#">shop now</a>--}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Single Slide -->
    <!-- Start Single Slide -->
    <div class="slide animation__style10 bg-image--7 fullscreen align__center--left">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="slider__content">
                        <div class="contentbox">
                            <h2>Buy <span>your </span></h2>
                            <h2>favourite <span>Book </span></h2>
                            <h2>from <span>Here </span></h2>
                            {{--                            <a class="shopbtn" href="#">shop now</a>--}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Single Slide -->
</div>
<!-- End Slider area -->

resources/views/exam1/quickview.blade.php
<div id="quickview-wrapper">
    <!-- Modal -->
    <div class="modal fade" id="productmodal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal__container" role="document">
            <div class="modal-content">
                <div class="modal-header modal__header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body">
                    <div class="modal-product">
                        <!-- Start product images -->
                        <div class="product-images">
                            <div class="main-image images">
                                <img alt="big images" src="{{ asset('img/product/big-img/1.jpg') }}">
                            </div>
                        </div>
                        <!-- end product images -->
                        <div class="product-info">
                            <h1>Simple Fabric Bags</h1>
                            <div class="rating__and__review">
                                <ul class="rating">
                                    <li><span class="ti-star"></span></li>
                                    <li><span class="ti-star"></span></li>
                                    <li><span class="ti-star"></span></li>
                                    <li><span class="ti-star"></span></li>
                                    <li><span class="ti-star"></span></li>
                                </ul>
                                <div class="review">
                                    <a href="#">4 customer reviews</a>
                                </div>
                            </div>
                            <div class="price-box-3">
                                <div class="s-price-box">
                                    <span class="new-price">$17.20</span>
                                    <span class="old-price">$45.00</span>
                                </div>
                            </div>
                            <div class="quick-desc">
                                Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates a modern look.
                            </div>
                            <div class="select__color">
                                <h2>Select color</h2>
                                <ul class="color__list">
                                    <li class="red"><a title="Red" href="#">Red</a></li>
                                    <li class="gold"><a title="Gold" href="#">Gold</a></li>
                                    <li class="orange"><a title="Orange" href="#">Orange</a></li>
                                    <li class="orange"><a title="Orange" href="#">Orange</a></li>
                                </ul>
                            </div>
                            <div class="select__size">
                                <h2>Select size</h2>
                                <ul class="color__list">
                                    <li class="l__size"><a title="L" href="#">L</a></li>
                                    <li class="m__size"><a title="M" href="#">M</a></li>
                                    <li class="s__size"><a title="S" href="#">S</a></li>
                                    <li class="xl__size"><a title="XL" href="#">XL</a></li>
                                    <li class="xxl__size"><a title="XXL" href="#">XXL</a></li>
                                </ul>
                            </div>
                            <div class="social-sharing">
                                <div class="widget widget_socialsharing_widget">
                                    <h3 class="widget-title-modal">Share this product</h3>
                                    <ul class="social__net social__net--2 d-flex justify-content-start">
                                        <li class="facebook">
                                            <a href="#" class="rss social-icon"><i class="zmdi zmdi-rss"></i></a>
                                        </li>
                                        <li class="linkedin">
                                            <a href="#" class="linkedin social-icon"><i class="zmdi zmdi-linkedin"></i></a>
                                        </li>
                                        <li class="pinterest">
                                            <a href="#" class="pinterest social-icon"><i class="zmdi zmdi-pinterest"></i></a>
                                        </li>
                                        <li class="tumblr">
                                            <a href="#" class="tumblr social-icon"><i class="zmdi zmdi-tumblr"></i></a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="addtocart-btn">
                                <a href="#">Add to cart</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>