routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/app', function () {
    return view('app');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/users', 'UsersController')->middleware(['auth']);

Route::resource('/books', 'BooksController');

Route::resource('/loaisachs', 'LoaisachsController');
Route::resource('/nhaxuatbans', 'NhaxuatbansController');
Route::resource('/tacgias', 'TacgiasController');

Route::resource('/carts', 'CartsController')->middleware(['auth']);

Route::get('/about', function () {
    return view('about');
})->name('about');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class User extends Authenticatable
{
    use Notifiable;

    protected $table = 'users';
    public $primaryKey = 'id';
    public $timestamps = true;

    protected $perPage = 10;

    protected $fillable = [
        'user_name',
        'password',
        'name',
        'address',
        'phone',
        'role',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    const ADMIN = 1;
    const STAFF = 2;
    const GUESS = 3;

    public static $roles = [
        self::ADMIN => 'Quản trị viên',
        self::STAFF => 'Nhân viên',
        self::GUESS => 'Người dùng',
    ];

    /**
     * Scope a query to find userName.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param string $userName
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeFindUserName($query, $userName)
    {
        return $query->where('user_name', 'like', '%' . $userName . '%');
    }

    /**
     * Scope a query to find name.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param string $name
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeFindName($query, $name)
    {
        return $query->where('name', 'like', '%' . $name . '%');
    }

    /**
     * Scope a query to find address.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param string $address
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeFindAddress($query, $address)
    {
        return $query->where('address', 'like', '%' . $address . '%');
    }

    /**
     * Scope a query to find phone.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param string $phone
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeFindPhone($query, $phone)
    {
        return $query->where('phone', $phone);
    }

    /**
     * get users info ascending sort by user_name
     *
     * @param array $data
     * @return \Illuminate\Pagination\Paginator
     */
    public function getUsers($data)
    {
        $builder = $this->orderBy('user_name');

        if (isset($data['user_name'])) {
            $builder->findUserName($data['user_name']);
        }
        if (isset($data['name'])) {
            $builder->findName($data['name']);
        }
        if (isset($data['address'])) {
            $builder->findAddress($data['address']);
        }
        if (isset($data['phone'])) {
            $builder->findPhone($data['phone'])->get();
        }

        return $builder->paginate();
    }

    /**
     * save  user to database
     *
     * @param \App\Http\Requests\StoreUserRequest $request
     * @return User
     */
    public function saveUser($request)
    {
        $data = $request->all();
        $data['password'] = Hash::make($data['password']);
        return $this->create($data);
    }

    /**
     * update user in database
     *
     * @param StoreUserRequest $request
     * @return boolean
     */
    public function updateUser($request)
    {
        $data = $request->all();

        if (Auth::id() == $request->id) {
            $data['user_name'] = Auth::user()->user_name;
        }

        if ($data['password']) {
            $data['password'] = Hash::make($data['password']);
        } else {
            unset($data['password']);
        }

        return $this->find($request->id)->update($data);
    }

    /**
     * delete user from database
     *
     * @param integer $id
     * @return bool
     */
    public function deleteUser($id)
    {
        $user = $this->find($id);
        if (!isset($user)) {
            return false;
        }

        return $user->delete();
    }

    public function orders()
    {
        $this->hasMany('App\Models\Order');
    }

    public function orderdetails()
    {
        $this->hasMany('App\Models\Orderdetail');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreUserRequest;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;

class UsersController extends Controller
{
    protected $user;

    /**
     * construct class
     *
     * UsersController constructor.
     * @param User $user
     */
    public function __construct(User $user)
    {
        $this->user = $user;
//        $this->middleware()
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if (Gate::allows('admin', Auth::user()) || Gate::allows('staff', Auth::user())) {
            $users = $this->user->getUsers($request->all());

            return view('users/index')->with('users', $users);
        } else {
            return redirect()->route('home');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Gate::allows('admin', Auth::user()) || Gate::allows('staff', Auth::user())) {
            if (Gate::allows('admin', Auth::user())) {
                return view('users/create');
            }
            flash('Ban khong co quyen truy cap')->error();
            return redirect()->route('users.index');
        } else {
            return redirect()->route('home');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\StoreUserRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUserRequest $request)
    {
        if (Gate::allows('admin', Auth::user()) || Gate::allows('staff', Auth::user())) {
            if (Gate::allows('staff', Auth::user())) {
                flash('Ban khong co du quyen')->error();
                return redirect()->route('users.index');
            }

            $user = $this->user->saveUser($request);

            if ($user != null) {
                //set success message
                flash('add thanh cong')->success();
            }

            return redirect()->route('users.index');
        } else {
            return redirect()->route('home');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (Auth::user()->id == $id) {
            return view('users.show');
        }

        return redirect()->route('home');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Gate::allows('admin', Auth::user())) {
            $user = $this->user->find($id);
            if (!isset($user)) {
                flash('cap nhat that bai')->error();
                return redirect()->route('users.index');
            }
            return view('users/edit')->with('user', $user);
        } elseif (Auth::user()->id == $id) {
//            $user = $this->user->find($id);
            return view('users/edit')->with('user', Auth::user());
        } elseif (Gate::allows('staff', Auth::user())) {
            flash('Ban khong co du quyen')->error();
            return redirect()->route('users.index');
        } else
            return redirect()->route('home');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\StoreUserRequest $request
     * @return \Illuminate\Http\Response
     */
    public function update(StoreUserRequest $request)
    {
        if (Gate::allows('admin', Auth::user())) {
            if ($this->user->updateUser($request)) {
                flash('Cap nhat thanh cong')->success();
            } else {
                flash('Cap nhat that bai')->error();
            }
            return redirect()->route('users.index');
        } elseif (Auth::user()->id == $request->id) {
            if ($this->user->updateUser($request)) {
                flash('Cap nhat thanh cong')->success();
            } else {
                flash('Cap nhat that bai')->error();
            }
            return redirect()->route('users.show', Auth::id());
        } elseif (Gate::allows('staff', Auth::user())) {
            flash('Ban khong co du quyen')->error();
            return redirect()->route('users.index');
        } else {
            return redirect()->route('home');
        }

    }

    /**
     * Remove user from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Gate::allows('admin', Auth::user()) || Gate::allows('staff', Auth::user())) {

            if (Gate::allows('staff', Auth::user())) {
                flash('Ban khong co du quyen')->error();
                return redirect()->route('users.index');
            }

            //Check if user exists before deleting
            if ($this->user->deleteUser($id)) {
                flash('Xoa thanh cong')->success();
            } else {
                flash('Xoa that bai')->error();
            }

            return redirect()->route('users.index');
        } else
            return redirect()->route('home');
    }
}

resources/views/users/create.blade.php
@extends('layouts.admin')

@section('title', 'Thêm mới người dùng')

@section('content')
    <br>
    <br>

    <h3>Đăng ký</h3>
    <form action="{{ route('users.store') }}" method="post">
        @csrf
        @include('users.form')
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Đăng ký</button>
        </div>
    </form>

    <br>
    <br>
@endsection

resources/views/users/edit.blade.php
@extends('exam1.default')

@section('title', 'Cập nhật người dùng')

@section('content')
    <br>
    <br>
    <div class="container">
        <br>
        <h3>Cập nhật</h3>
        <form action="{{ route('users.update', $user->id) }}" method="post">
            @csrf
            @method('PUT')
            <input type="hidden" name="id" value="{{ $user->id }}">
            @include('users.form')

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Cập nhật</button>
            </div>
        </form>
    </div>
    <br>
    <br>
@endsection

resources/views/users/form.blade.php
{{--user name--}}
@can('admin')
    <div class="form-group row">
        <label for="user-name" class="col-sm-2 col-form-label @error('user_name') text-danger @enderror">User Name</label>
        <div class="col-sm-5">
            <input type="text" class="form-control @error('user_name') is-invalid @enderror" id="user-name" name="user_name" value="{{ old('user_name') ?? $user->user_name ?? null }}">
            @error('user_name')
            <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>
    </div>
@endcan
@cannot('admin')
    <input type="hidden" name="user_name" value="{{ $user->user_name }}">
@endcannot

{{--Mật khẩu--}}
<div class="form-group row">
    <label for="password" class="col-sm-2 col-form-label @error('password') text-danger @enderror">Mật khẩu</label>
    <div class="col-sm-5">
        <input type="password" class="form-control @error('password') is-invalid @enderror" id="password" name="password">
        @error('password')
        <div class="text-danger">{{ $message }}</div>
        @enderror
    </div>
</div>

{{--Mật khẩu xác nhận--}}
<div class="form-group row">
    <label for="password-confirmation" class="col-sm-2 col-form-label @error('password_confirmation') text-danger @enderror">Mật khẩu xác nhận</label>
    <div class="col-sm-5">
        <input type="password" class="form-control @error('password_confirmation') is-invalid @enderror" id="password-confirmation" name="password_confirmation">
        @error('password_confirmation')
        <div class="text-danger">{{ $message }}</div>
        @enderror
    </div>
</div>

{{--Tên--}}
<div class="form-group row">
    <label for="name" class="col-sm-2 col-form-label @error('name') text-danger @enderror">Tên</label>
    <div class="col-sm-5">
        <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name') ?? $user->name ?? null }}">
        @error('name')
        <div class="text-danger">{{ $message }}</div>
        @enderror
    </div>
</div>

{{--Địa chỉ--}}
<div class="form-group row">
    <label for="address" class="col-sm-2 col-form-label @error('address') text-danger @enderror">Địa chỉ</label>
    <div class="col-sm-5">
        <input type="text" class="form-control  @error('address') is-invalid @enderror" id="address" name="address" value="{{ old('address') ?? $user->address ?? null }}">
        @error('address')
        <div class="text-danger">{{ $message }}</div>
        @enderror
    </div>
</div>

{{--Số điện thoại--}}
<div class="form-group row">
    <label for="phone" class="col-sm-2 col-form-label @error('phone') text-danger @enderror">Số điện thoại</label>
    <div class="col-sm-5">
        <input type="tel" class="form-control @error('phone') is-invalid @enderror" id="phone" name="phone" value="{{ old('phone') ?? $user->phone ?? null }}">
        @error('phone')
        <div class="text-danger">{{ $message }}</div>
        @enderror
    </div>
</div>

{{--role--}}
@can('admin')
    <div class="form-group row @cannot('admin') hidden @endcannot">
        <label class="col-sm-2 col-form-label">Chọn quyền</label>
        <div class="col-sm-5">
            <select class="browser-default custom-select" name="role">
                @php
                    $roles = \App\Models\User::$roles;
                @endphp

                @foreach($roles as $key => $value)
                    <option value="{{ $key }}" {{ ((old('role') ?? $user->role ?? 0) == $key) ? 'selected' : '' }}>{{ $value }}</option>
                @endforeach
            </select>
        </div>
    </div>
@endcan
@cannot('admin')
    <input type="hidden" name="role" value="3">
@endcannot

resources/views/users/index.blade.php
@extends('layouts.admin')

@section('title', 'Danh sách người dùng')

@section('content')
    <br>
    <div class="container">
        @include('flash::message')

        <div class="container">
            <form action="{{ route('users.index') }}" class="form-group" method="get">
                @csrf
                <div class="row">
                    <div class="col-auto">
                        <input class="form-control mr-sm-0" type="search" placeholder="User Name" name="user_name" value="{{ request('user_name') }}">
                    </div>
                    <div class="col-auto">
                        <input class="form-control mr-sm-0" type="search" placeholder="Tên" name="name" value="{{ request('name') }}">
                    </div>
                    <div class="col-auto">
                        <input class="form-control mr-sm-0" type="search" placeholder="Địa chỉ" name="address" value="{{ request('address') }}">
                    </div>
                    <div class="col-auto">
                        <input class="form-control mr-sm-0" type="search" placeholder="Số điện thoại" name="phone" value="{{ request('phone') }}">
                    </div>
                </div>

                <button class="btn btn-primary my-2 my-sm-10 container d-flex justify-content-center" type="submit">Search</button>
            </form>
        </div>

        <br>
        @if(count($users))
            <table class="table">
                <thead class="thead-light text-center">
                    <tr>
                        <th>STT</th>
                        <th>Account</th>
                        <th>Tên</th>
                        <th>Địa chỉ</th>
                        <th>SĐT</th>
                        <th width="120">Role</th>
                        @can('admin')
                            <th width="230">Hành động</th>
                        @endcan
                    </tr>
                </thead>

                @foreach($users as $key => $user)
                    <tr class="text-left">
                        <td>{{ $users->firstItem() + $key }}</td>
                        <td>{{ $user->user_name }}</td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->address }}</td>
                        <td>{{ $user->phone }}</td>
                        <td>{{ \App\Models\User::$roles[$user->role] }}</td>

                        @can('admin')
                            <td>
                                <a class="btn btn-primary" href="{{ route('users.edit', $user->id) }}">Cập nhật</a>
                                <button data-toggle="modal" onclick="deleteData({{ $user->id }})" data-target="#delete-modal" class="btn btn-xs btn-danger">Xóa</button>
                            </td>
                        @endcan
                    </tr>
                @endforeach
            </table>
            {!! $users->appends(request()->input())->links() !!}
        @else
            <p class="text-center">Không có kết quả tìm kiếm.</p>
        @endif
    </div>

    <div id="delete-modal" class="modal fade text-danger" role="dialog">
        <div class="modal-dialog ">
            <!-- Modal content-->
            <form action="" id="delete-form" method="post">
                <div class="modal-content">
                    <div class="modal-header bg-danger">
                        <h4 class="modal-title text-center text-dark">DELETE CONFIRMATION</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>

                    <div class="modal-body">
                        @csrf
                        @method('delete')
                        <p class="text-center">Bạn có chắc chắn muốn xoá bản ghi này không?</p>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" data-dismiss="modal">Huỷ</button>
                        <button type="submit" name="" class="btn btn-danger" data-dismiss="modal" onclick="formSubmit()">OK</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <script type="text/javascript">
        function deleteData(id) {
            var id = id;
            var url = '{{ route("users.destroy", ":id") }}';
            url = url.replace(':id', id);
            $("#delete-form").attr('action', url);
        }

        function formSubmit() {
            $("#delete-form").submit();
        }
    </script>
@endsection

resources/views/users/show.blade.php
@extends('exam1.default')

@section('title', 'Profile')

@section('content')

    <div class="box-search-content search_active block-bg close__top">
        <form id="search_mini_form" class="minisearch" action="#">
            <div class="field__search">
                <input type="text" placeholder="Search entire store here...">
                <div class="action">
                    <a href="#"><i class="zmdi zmdi-search"></i></a>
                </div>
            </div>
        </form>
        <div class="close__wrap">
            <span>close</span>
        </div>
    </div>
    <!-- End Search Popup -->

    <!-- Start main Content -->
    <div class="maincontent bg--white pt--80 pb--55">
        <div class="container">
            @include('flash::message')
            <div class="row">
                <div class="col-lg-9 col-12">
                    <div class="wn__single__product">
                        <div class="row">
                            <div class="col-lg-6 col-12">
                                <div class="wn__fotorama__wrapper">
                                    <div class="fotorama wn__fotorama__action" data-nav="thumbs">
                                        <a href="1.jpg"><img src="/img/product/1.jpg" alt=""></a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 col-12">
                                <div class="product__info__main">
                                    <h1>{{ Auth::user()->name }}</h1>

                                    <div class="product__overview">
                                        <p>Address: {{ Auth::user()->address }}</p>
                                        <p>Phone: {{ Auth::user()->phone }}</p>
                                        <a class="btn btn-primary" href="{{ route('users.edit', Auth::user()->id) }}">edit</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End main Content -->
    <!-- Start Search Popup -->
    <div class="box-search-content search_active block-bg close__top">
        <form id="search_mini_form--2" class="minisearch" action="#">
            <div class="field__search">
                <input type="text" placeholder="Search entire store here...">
                <div class="action">
                    <a href="#"><i class="zmdi zmdi-search"></i></a>
                </div>
            </div>
        </form>
        <div class="close__wrap">
            <span>close</span>
        </div>
    </div>
    <!-- End Search Popup -->
@endsection