routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/app', function () {
    return view('app');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/users', 'UsersController')->middleware(['auth']);

Route::resource('/books', 'BooksController');

Route::resource('/loaisachs', 'LoaisachsController');
Route::resource('/nhaxuatbans', 'NhaxuatbansController');
Route::resource('/tacgias', 'TacgiasController');

Route::resource('/carts', 'CartsController')->middleware(['auth']);

Route::get('/about', function () {
    return view('about');
})->name('about');

app/Models/Loaisach.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Loaisach extends Model
{
    protected $table = 'loaisachs';

    public $primaryKey = 'id';
    public $timestamps = true;

    protected $fillable = [
        'name',
    ];

    protected $perPage = 5;

    public function allLoaisachCount()
    {
        return $this->withCount('books')->orderBy('name')->get();
    }

    public function saveLoaisach($request)
    {
        $data = $request->all();
        Loaisach::create($data);
    }
  
    public function updateLoaisach($request)
    {
        $data = $request->all();
        return $this->find($request->id)->update($data);
    }

    public function books()
    {
        return $this->hasMany('App\Models\Book');
    }
}

app/Http/Controllers/LoaisachsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Book;
use App\Models\Loaisach;
use Illuminate\Http\Request;

class LoaisachsController extends Controller
{
    protected $loaisach;

    public function __construct(Loaisach $loaisach)
    {
        $this->loaisach = $loaisach;
        $this->middleware(['auth','manager'])->except(['index', 'show']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $loaisachs = $this->loaisach->orderBy('name')->paginate();
        return view('loaisachs.index')->with('loaisachs', $loaisachs);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('loaisachs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->loaisach->saveLoaisach($request);

        flash('add success')->success();

        return redirect()->route('loaisachs.index');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $loaisach = $this->loaisach->find($id);
        $loaisachs = $this->loaisach->allLoaisachCount();
        $book = new Book();
        $books = $book->findLoaisach($id)->paginate(12);
        return view('loaisachs.show')->with(['main_loaisach' => $loaisach, 'books' => $books,'loaisachs' => $loaisachs]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $loaisach = $this->loaisach->find($id);
        return view('loaisachs.edit')->with('loaisach', $loaisach);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->loaisach->updateLoaisach($request);

        flash('update success')->success();

        return redirect()->route('loaisachs.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->loaisach->find($id)->delete();

        flash('delete success')->error();

        return redirect()->route('loaisachs.index');
    }
}

resources/views/loaisachs/create.blade.php
@extends('exam1.default')

@section('title', 'Add Loaisach')

@section('content')
    <div class="cart-main-area section-padding--lg bg--white">
        <div class="container">
            <br>
            <h1>Add Loaisach</h1>
            <form action="{{ route('loaisachs.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                @include('loaisachs.form')
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">ADD LOAISACH</button>
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/loaisachs/edit.blade.php
@extends('exam1.default')

@section('title', 'edit loaisach')

@section('content')
    <div class="cart-main-area section-padding--lg bg--white">
        <div class="container">
            <br>
            <h1>Edit Loaisach</h1>
            <form action="{{ route('loaisachs.update', $loaisach->id) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <input type="hidden" name="id" value="{{ $loaisach->id }}">

                @include('loaisachs.form')
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">EDIT LOAISACH</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/loaisachs/form.blade.php
{{--loaisach name--}}
<div class="form-group row">
    <label for="name" class="col-sm-2 col-form-label @error('name') text-danger @enderror">Name</label>
    <div class="col-sm-5">
        <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name') ?? $loaisach->name ?? null }}">
        @error('name')
        <div class="text-danger">{{ $message }}</div>
        @enderror
    </div>
</div>


resources/views/loaisachs/index.blade.php
@extends('exam1.default')

@section('title', 'Book type list')

@section('content')
    <div class="cart-main-area section-padding--lg bg--white">
        <div class="container">
            <br><br><br><br>
	    @canany(['admin','staff'])
                                <a class="btn btn-primary" href="{{ route('loaisachs.create') }}">Create Loai sach</a>
                                <br><br>
                            @endcanany
            @include('flash::message')

            <h1>Loaisachs</h1>
            @if(count($loaisachs)>0)
                @foreach($loaisachs as $key => $loaisach)
                    <div class="card card-body bg-light">
                        <div class="row">
                            <div class="col-md-4 col-sm-4">
                                <a href="/loaisachs/{{$loaisach->id}}"></a>
                            </div>

                            <div class="col-md-8">
                                <div>
                                    <h3>{{ $loaisachs->firstItem() + $key }} .
                                        <a href="/loaisachs/{{$loaisach->id}}"> {{ $loaisach->name }}</a>
                                    </h3>
                                    <small>update on {{ $loaisach->created_at }}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br>
                @endforeach
            @endif
            {!! $loaisachs->links() !!}

            <br><br><br><br>
        </div>
    </div>
@endsection

resources/views/loaisachs/show.blade.php
@extends('exam1.default')

@section('title', $main_loaisach->name)

@section('content')
    <div class="cart-main-area section-padding--lg bg--white">
        <div class="container">
            @include('flash::message')

            @canany(['admin','staff'])
                <br><br>
                <div style="text-align: center">
                    <h1>{{ $main_loaisach->name }}</h1>

                    <a class="btn btn-primary" href="{{ route('loaisachs.edit', $main_loaisach->id) }}">Edit</a>
                    <form action="{{ route('loaisachs.destroy', $main_loaisach->id) }}" method="post">
                        @csrf
                        @method('DELETE')

                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </div>
                <br><br>
            @endcanany

            <div class="row">
                <div class="col-lg-3 col-12 order-2 order-lg-1 md-mt-40 sm-mt-40">
                    <div class="shop__sidebar">
                        <aside class="wedget__categories poroduct--cat">
                            <h3 class="wedget__title">Categories</h3>
                            <ul>
                                <li><a href="{{ route('books.index') }}">All<span>(@php
                                                $x=0;
                                                foreach ($loaisachs as $loaisach){
                                                $x+=$loaisach->books_count;
                                                }
                                            echo $x;
                                            @endphp)</span></a></li>
                                @foreach($loaisachs as $loaisach)
                                    <li>
                                        <a href="{{ route('loaisachs.show', $loaisach->id) }}">{{ $loaisach->name }}
                                            <span>({{ count($loaisach->books) }})</span>
                                        </a>
                                    </li>
                                @endforeach
                            </ul>
                        </aside>
                        <aside class="wedget__categories pro--range">
                            <h3 class="wedget__title">Filter by price</h3>
                            <div class="content-shopby">
                                <div class="price_filter s-filter clear">
                                    <form action="#" method="GET">
                                        <div id="slider-range"></div>
                                        <div class="slider__range--output">
                                            <div class="price__output--wrap">
                                                <div class="price--output">
                                                    <span>Price :</span><input type="text" id="amount" readonly="">
                                                </div>
                                                <div class="price--filter">
                                                    <a href="#">Filter</a>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </aside>

                        <aside class="wedget__categories sidebar--banner">
                            <img src="{{ asset('img/others/banner_left.jpg') }}" alt="banner images">
                            <div class="text">
                                <h2>new products</h2>
                                <h6>save up to <br> <strong>40%</strong>off</h6>
                            </div>
                        </aside>
                    </div>
                </div>
                {{--                end left page--}}

                <div class="col-lg-9 col-12 order-1 order-lg-2">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="shop__list__wrapper d-flex flex-wrap flex-md-nowrap justify-content-between">
                                <div class="shop__list nav justify-content-center" role="tablist">
                                    <a class="nav-item nav-link active" data-toggle="tab" href="#nav-grid" role="tab"><i class="fa fa-th"></i></a>
                                    <a class="nav-item nav-link" data-toggle="tab" href="#nav-list" role="tab"><i class="fa fa-list"></i></a>
                                </div>
                                <p>Total {{ $books->total() }} books</p>
                                <div class="orderby__wrapper"></div>
                            </div>
                        </div>
                    </div>
                    <div class="tab__container">
                        <div class="shop-grid tab-pane fade show active" id="nav-grid" role="tabpanel">
                            <div class="row">
                            @foreach($books as $key => $book)
                                <!-- Start Single Product -->
                                    <div class="product product__style--3 col-lg-4 col-md-4 col-sm-6 col-12">
                                        <div class="product__thumb">
                                            @if(isset($book->image))
                                                <a class="first__img" href="{{ route('books.show', $book->id) }}"><img src="/storage/book_images/{{ $book->image }}"></a>
                                                {{--                                        <a class="second__img animation1" href="single-product.html"><img src="{{ asset('img/books/2.jpg') }}" alt="product image"></a>--}}
                                            @else
                                                <a class="first__img" href="{{ route('books.show', $book->id) }}"><img src="{{ asset('img/default_book.jpg') }}"></a>
                                            @endif
                                            <div class="hot__box">
                                            </div>
                                        </div>
                                        <div class="product__content content--center">
                                            <h4><a href="{{ route('books.show', $book->id) }}">{{ $book->name }}</a>
                                            </h4>
                                            <ul class="prize d-flex">
                                                <li>{{ $book->price }}$</li>
                                                {{--                                                <li class="old_prize">$35.00</li>--}}
                                            </ul>
                                            <div class="action">
                                                <div class="actions_inner">
                                                    <ul class="add_to_links">
                                                        <li>
                                                            <a class="cart" href="cart.html"><i class="bi bi-shopping-bag4"></i></a>
                                                        </li>
                                                        <li>
                                                            <a class="wishlist" href="{{ route('carts.show', $book->id) }}"><i class="bi bi-shopping-cart-full"></i></a>
                                                        </li>
                                                        <li>
                                                            <a class="compare" href="#"><i class="bi bi-heart-beat"></i></a>
                                                        </li>
                                                        <li>
                                                            <a data-toggle="modal" title="Quick View" class="quickview modal-view detail-link" href="#productmodal"><i class="bi bi-search"></i></a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="product__hover--content">
                                                <ul class="rating d-flex">
                                                    <li class="on"><i class="fa fa-star-o"></i></li>
                                                    <li class="on"><i class="fa fa-star-o"></i></li>
                                                    <li class="on"><i class="fa fa-star-o"></i></li>
                                                    <li><i class="fa fa-star-o"></i></li>
                                                    <li><i class="fa fa-star-o"></i></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- End Single Product -->
                            @endforeach
                            <!-- Start Single Product -->

                                <!-- End Single Product -->
                            </div>
                            {!! $books->appends(request()->input())->links() !!}
                        </div>


                        <div class="shop-grid tab-pane fade" id="nav-list" role="tabpanel">
                            <div class="list__view__wrapper">
                                <!-- Start Single Product -->
                                @foreach($books as $book)
                                    <div class="list__view">
                                        <div class="thumb">
                                            @if(isset($book->image))
                                                <a class="first__img" href="{{ route('books.show', $book->id) }}"><img src="/storage/book_images/{{ $book->image }}" alt="product images"></a>
                                            @else
                                                <a class="first__img" href="{{ route('books.show', $book->id) }}"><img src="/img/books/default_book.jpg" alt="product images"></a>
                                            @endif
                                        </div>
                                        <div class="content">
                                            <h2><a href="single-product.html">{{ $book->name }}</a></h2>
                                            <ul class="rating d-flex">
                                                <li class="on"><i class="fa fa-star-o"></i></li>
                                                <li class="on"><i class="fa fa-star-o"></i></li>
                                                <li class="on"><i class="fa fa-star-o"></i></li>
                                                <li class="on"><i class="fa fa-star-o"></i></li>
                                                <li><i class="fa fa-star-o"></i></li>
                                                <li><i class="fa fa-star-o"></i></li>
                                            </ul>
                                            <ul class="prize__box">
                                                <li>${{ $book->price }}</li>
                                                {{--                                                <li class="old__prize">{{ $book->price }}$</li>--}}
                                            </ul>
                                            <p> DESCRIBE: {!! substr($book->desc,0,250) . ' ...' !!}</p>
                                            <ul class="cart__action d-flex">
                                                <li class="cart">
                                                    <a href="{{ route('carts.show', $book->id) }}">Add to cart</a>
                                                </li>
                                                <li class="wishlist"><a href="cart.html"></a></li>
                                                <li class="compare"><a href="cart.html"></a></li>
                                            </ul>

                                        </div>
                                    </div>
                                    <!-- End Single Product -->
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>


@endsection